export const URLs: { [key: string]: any } = {
  ATAC_50bs: {
    All_amacrine: "All_amacrine.RPKM.bw",
    Astrocyte: "Astrocyte.RPKM.bw",
    Cones: "Cones.RPKM.bw",
    Endothelial: "Endothelial.RPKM.bw",
    Fibroblasts: "Fibroblasts.RPKM.bw",
    GABA_amacrine: "GABA_amacrine.RPKM.bw",
    Gly_amacrine: "Gly_amacrine.RPKM.bw",
    Horizontal: "Horizontal.RPKM.bw",
    Macrophage: "Macrophage.RPKM.bw",
    Mast_cell: "Mast_cell.RPKM.bw",
    Melanocyte: "Melanocyte.RPKM.bw",
    Microglia: "Microglia.RPKM.bw",
    Muller_glia: "Muller_glia.RPKM.bw",
    OFF_cone_bipolar: "OFF_cone_bipolar.RPKM.bw",
    ON_cone_bipolar: "ON_cone_bipolar.RPKM.bw",
    Perictyes: "Perictyes.RPKM.bw",
    RGC: "RGC.RPKM.bw",
    RPE: "RPE.RPKM.bw",
    Rod_bipolar: "Rod_bipolar.RPKM.bw",
    Rods: "Rods.RPKM.bw",
    Schwann: "Schwann.RPKM.bw",
    T_NK_cell: "T_NK_cell.RPKM.bw",
    VSMC: "VSMC.RPKM.bw",
  },

  RNA_50bs: {
    All_amacrine: "All_amacrine.RPKM.bw",
    Astrocyte: "Astrocyte.RPKM.bw",
    Cones: "Cones.RPKM.bw",
    Endothelial: "Endothelial.RPKM.bw",
    Fibroblasts: "Fibroblasts.RPKM.bw",
    GABA_amacrine: "GABA_amacrine.RPKM.bw",
    Gly_amacrine: "Gly_amacrine.RPKM.bw",
    Horizontal: "Horizontal.RPKM.bw",
    Macrophage: "Macrophage.RPKM.bw",
    Mast_cell: "Mast_cell.RPKM.bw",
    Melanocyte: "Melanocyte.RPKM.bw",
    Microglia: "Microglia.RPKM.bw",
    Muller_glia: "Muller_glia.RPKM.bw",
    OFF_cone_bipolar: "OFF_cone_bipolar.RPKM.bw",
    ON_cone_bipolar: "ON_cone_bipolar.RPKM.bw",
    Perictyes: "Perictyes.RPKM.bw",
    RGC: "RGC.RPKM.bw",
    RPE: "RPE.RPKM.bw",
    Rod_bipolar: "Rod_bipolar.RPKM.bw",
    Rods: "Rods.RPKM.bw",
    Schwann: "Schwann.RPKM.bw",
    T_NK_cell: "T_NK_cell.RPKM.bw",
    VSMC: "VSMC.RPKM.bw",
  },

  hic_10K: {
    All_amacrine: "All_amacrine.hic",
    Astrocyte: "Astrocyte.hic",
    Cones: "Cones.hic",
    Endothelial: "Endothelial.hic",
    Fibroblasts: "Fibroblasts.hic",
    GABA_amacrine: "GABA_amacrine.hic",
    Gly_amacrine: "Gly_amacrine.hic",
    Horizontal: "Horizontal.hic",
    Macrophage: "Macrophage.hic",
    Mast_cell: "Mast_cell.hic",
    Melanocyte: "Melanocyte.hic",
    Muller_glia: "Muller_glia.hic",
    OFF_cone_bipolar: "OFF_cone_bipolar.hic",
    ON_cone_bipolar: "ON_cone_bipolar.hic",
    Perictyes: "Perictyes.hic",
    RGC: "RGC.hic",
    RPE: "RPE.hic",
    Rod_bipolar: "Rod_bipolar.hic",
    Rods: "Rods.hic",
    Schwann: "Schwann.hic",
    T_NK_cell: "T_NK_cell.hic",
    VSMC: "VSMC.hic",
  },

  hic_25K: {
    All_amacrine: "All_amacrine.hic",
    Astrocyte: "Astrocyte.hic",
    Cones: "Cones.hic",
    Endothelial: "Endothelial.hic",
    Fibroblasts: "Fibroblasts.hic",
    GABA_amacrine: "GABA_amacrine.hic",
    Gly_amacrine: "Gly_amacrine.hic",
    Horizontal: "Horizontal.hic",
    Macrophage: "Macrophage.hic",
    Mast_cell: "Mast_cell.hic",
    Melanocyte: "Melanocyte.hic",
    Muller_glia: "Muller_glia.hic",
    OFF_cone_bipolar: "OFF_cone_bipolar.hic",
    ON_cone_bipolar: "ON_cone_bipolar.hic",
    Perictyes: "Perictyes.hic",
    RGC: "RGC.hic",
    RPE: "RPE.hic",
    Rod_bipolar: "Rod_bipolar.hic",
    Rods: "Rods.hic",
    Schwann: "Schwann.hic",
    T_NK_cell: "T_NK_cell.hic",
    VSMC: "VSMC.hic",
  },
  hic_100K: {
    All_amacrine: "All_amacrine.hic",
    Astrocyte: "Astrocyte.hic",
    Cones: "Cones.hic",
    Endothelial: "Endothelial.hic",
    Fibroblasts: "Fibroblasts.hic",
    GABA_amacrine: "GABA_amacrine.hic",
    Gly_amacrine: "Gly_amacrine.hic",
    Horizontal: "Horizontal.hic",
    Macrophage: "Macrophage.hic",
    Mast_cell: "Mast_cell.hic",
    Melanocyte: "Melanocyte.hic",
    Muller_glia: "Muller_glia.hic",
    OFF_cone_bipolar: "OFF_cone_bipolar.hic",
    ON_cone_bipolar: "ON_cone_bipolar.hic",
    Perictyes: "Perictyes.hic",
    RGC: "RGC.hic",
    RPE: "RPE.hic",
    Rod_bipolar: "Rod_bipolar.hic",
    Rods: "Rods.hic",
    Schwann: "Schwann.hic",
    T_NK_cell: "T_NK_cell.hic",
    VSMC: "VSMC.hic",
  },
  mC_bw: {
    All_amacrine: [
      "All_amacrine.CGN-both.frac.bw",
      "All_amacrine.CHN.CHN-both.frac.bw",
    ],
    Astrocyte: ["Astrocyte.CGN-both.frac.bw", "Astrocyte.CHN.CHN-both.frac.bw"],
    Cones: ["Cones.CGN-both.frac.bw", "Cones.CHN.CHN-both.frac.bw"],
    Endothelial: [
      "Endothelial.CGN-both.frac.bw",
      "Endothelial.CHN-both.frac.bw",
    ],
    Fibroblasts: [
      "Fibroblasts.CGN-both.frac.bw",
      "Fibroblasts.CHN-both.frac.bw",
    ],
    GABA_amacrine: [
      "GABA_amacrine.CGN-both.frac.bw",
      "GABA_amacrine.CHN.CHN-both.frac.bw",
    ],
    Gly_amacrine: [
      "Gly_amacrine.CGN-both.frac.bw",
      "Gly_amacrine.CHN.CHN-both.frac.bw",
    ],
    Horizontal: [
      "Horizontal.CGN-both.frac.bw",
      "Horizontal.CHN.CHN-both.frac.bw",
    ],
    Macrophage: ["Macrophage.CGN-both.frac.bw", "Macrophage.CHN-both.frac.bw"],
    Mast_cell: ["Mast_cell.CGN-both.frac.bw", "Mast_cell.CHN-both.frac.bw"],
    Melanocyte: ["Melanocyte.CGN-both.frac.bw", "Melanocyte.CHN-both.frac.bw"],
    Muller_glia: [
      "Muller_glia.CGN-both.frac.bw",
      "Muller_glia.CHN.CHN-both.frac.bw",
    ],
    OFF_cone_bipolar: [
      "OFF_cone_bipolar.CGN-both.frac.bw",
      "OFF_cone_bipolar.CHN.CHN-both.frac.bw",
    ],
    ON_cone_bipolar: [
      "ON_cone_bipolar.CGN-both.frac.bw",
      "ON_cone_bipolar.CHN.CHN-both.frac.bw",
    ],
    Perictyes: ["Perictyes.CGN-both.frac.bw", "Perictyes.CHN-both.frac.bw"],
    RGC: ["RGC.CGN-both.frac.bw", "RGC.CHN.CHN-both.frac.bw"],
    RPE: ["RPE.CGN-both.frac.bw", "RPE.CHN-both.frac.bw"],
    Rod_bipolar: [
      "Rod_bipolar.CGN-both.frac.bw",
      "Rod_bipolar.CHN.CHN-both.frac.bw",
    ],
    Rods: ["Rods.CGN-both.frac.bw", "Rods.CHN.CHN-both.frac.bw"],
    Schwann: ["Schwann.CGN-both.frac.bw", "Schwann.CHN-both.frac.bw"],
    T_NK_cell: ["T_NK_cell.CGN-both.frac.bw", "T_NK_cell.CHN-both.frac.bw"],
    VSMC: ["VSMC.CGN-both.frac.bw", "VSMC.CHN-both.frac.bw"],
  },
};
